### ISSUE TITLE
"sudo batctl if" command on gateway node results in "wlan0: <error reading status>"

### ISSUE THREAD

**Issue by gsleo1976** [binnes/WiFiMeshRaspberryPi#6] opened 2021-02-13 15:50 UTC
Hello Brian,

Creating my request as a new issue. Apologies, earlier I was posting on a closed thread.
My hardware and software details are as following 
**Gateway**
Raspberry Pi 2 Model B Rev 1.1
5.10.11-v7+ #1399 SMP Thu Jan 28 12:06:05 GMT 2021 armv7l GNU/Linux
USB WiFi (Realtek Semiconductor Corp. RTL8188CUS 802.11n WLAN Adapter)

**Bridge**
Raspberry Pi 4 Model B Rev 1.2
5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
On-board WiFi

**Issue details**

Sometimes back I followed your instructions and successfully created the mesh network 
But I tried today again and it shows me error "wlan0: error reading status".

I have closely tried all the instructions twice with a fresh image from Raspberry site.
I am configuring one Pi for Gateway and another for Bridge.
Followed the instructions very closely in Part1.
But it shows same error like this

pi@rpi-brg-4gb:~ $ sudo batctl if
wlan0: error reading status

**my gateway looks like this**

pi@rpi-gtw-1gb:~ $ ifconfig
bat0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1468
inet 192.168.199.1 netmask 255.255.255.0 broadcast 192.168.199.255
inet6 fe80::36c5:e5f6:4e13:9df8 prefixlen 64 scopeid 0x20
ether 1e:1a:0c:49:4c:81 txqueuelen 1000 (Ethernet)
RX packets 21 bytes 1460 (1.4 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 3 bytes 304 (304.0 B)
TX errors 0 dropped 45 overruns 0 carrier 0 collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
inet 192.168.1.34 netmask 255.255.255.0 broadcast 192.168.1.255
inet6 fe80::d6aa:4ac5:b976:548a prefixlen 64 scopeid 0x20
ether b8:27:eb:9f:ee:3b txqueuelen 1000 (Ethernet)
RX packets 1187 bytes 59140 (57.7 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 117 bytes 14893 (14.5 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING> mtu 65536
inet 127.0.0.1 netmask 255.0.0.0
inet6 ::1 prefixlen 128 scopeid 0x10
loop txqueuelen 1000 (Local Loopback)
RX packets 95 bytes 7546 (7.3 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 95 bytes 7546 (7.3 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
inet6 fe80::7edd:90ff:fe47:4507 prefixlen 64 scopeid 0x20
ether 7c:dd:90:47:45:07 txqueuelen 1000 (Ethernet)
RX packets 117 bytes 9729 (9.5 KiB)
RX errors 0 dropped 4 overruns 0 frame 0
TX packets 133 bytes 13669 (13.3 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

pi@rpi-gtw-1gb:~ $ iwconfig
lo no wireless extensions.

eth0 no wireless extensions.

wlan0 IEEE 802.11 ESSID:"call-code-mesh"
Mode:Ad-Hoc Frequency:2.412 GHz Cell: EE:99:7A:6C:F5:07
Tx-Power=20 dBm
Retry short limit:7 RTS thr=2347 B Fragment thr:off
Power Management:on

bat0 no wireless extensions.

pi@rpi-gtw-1gb:~ $ sudo batctl if
wlan0:

pi@rpi-gtw-1gb:~ $ sudo batctl n
Error - interface bat0 is not present or not a batman-adv interface

**my bridge looks like this**

pi@rpi-brg-4gb:~ $ ifconfig
bat0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1468
inet6 fe80::8a6:7ff:feb8:a14a prefixlen 64 scopeid 0x20
ether 0a:a6:07:b8:a1:4a txqueuelen 1000 (Ethernet)
RX packets 33 bytes 1386 (1.3 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 3557 bytes 213767 (208.7 KiB)
TX errors 0 dropped 225 overruns 0 carrier 0 collisions 0

br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1468
inet 192.168.1.4 netmask 255.255.255.0 broadcast 192.168.1.255
inet6 fe80::8a6:7ff:feb8:a14a prefixlen 64 scopeid 0x20
ether 0a:a6:07:b8:a1:4a txqueuelen 1000 (Ethernet)
RX packets 3995 bytes 197842 (193.2 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 286 bytes 31309 (30.5 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
inet6 fe80::dea6:32ff:feb7:dd6b prefixlen 64 scopeid 0x20
ether dc:a6:32:b7:dd:6b txqueuelen 1000 (Ethernet)
RX packets 4031 bytes 257826 (251.7 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 331 bytes 33904 (33.1 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING> mtu 65536
inet 127.0.0.1 netmask 255.0.0.0
inet6 ::1 prefixlen 128 scopeid 0x10
loop txqueuelen 1000 (Local Loopback)
RX packets 8 bytes 480 (480.0 B)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 8 bytes 480 (480.0 B)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
inet6 fe80::dea6:32ff:feb7:dd6c prefixlen 64 scopeid 0x20
ether dc:a6:32:b7:dd:6c txqueuelen 1000 (Ethernet)
RX packets 94 bytes 6715 (6.5 KiB)
RX errors 0 dropped 1 overruns 0 frame 0
TX packets 359 bytes 37300 (36.4 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

pi@rpi-brg-4gb:~ $ sudo brctl show
bridge name bridge id STP enabled interfaces
br0 8000.0aa607b8a14a no bat0
eth0

pi@rpi-brg-4gb:~ $ sudo batctl if
wlan0: error reading status

pi@rpi-brg-4gb:~ $ sudo batctl n
Error - interface bat0 is not present or not a batman-adv interface.

Please suggest me what could be the possible reason for this.
your guide is excellent material on mesh networking.
Thanks for educating the community on mesh networking.

Regards
Leo

**Comment by jrauh431** [comment] 2021-02-21 03:47
Same issue..

Gateway: Raspberry Pi 4 Model B Rev 1.4p

**Comment by jw2476** [comment] 2021-02-22 16:33
Same here

**Comment by steros76** [comment] 2021-02-27 14:52
Same problem on Raspberry Pi Zero W (Buster 10.8 up-to-date).
Note that "/sys/class/net/wlan0/batman_adv" is missing.

**Comment by torkel** [comment] 2021-02-28 09:33
Im not fully sure yet, but I think this is due to that batman-adv and batctl are very old in default packages from Raspberry OS.
I have downloaded latest batman-adv from https://www.open-mesh.org/ and compiled it.
Then I do not get "wlan0: error reading status" and "Error - interface bat0 is not present or not a batman-adv interface."

Have some things left to test but looks promising with new versions.

**Comment by jw2476** [comment] 2021-02-28 17:28
I've done some testing and it looks like the issue is with batctl instead, there's a massive version desync with batman-adv module (v2020.4) and batctl present in the raspberry pi repository (v2019.0) and with the latest update of the raspberry pi kernel (from 5.4 to 5.10) this gap has broken batman-adv. 

This can be fixed with the following which updates batctl:
```bash
sudo apt purge batctl -y &&  \
sudo apt install libnl-genl-3-dev libnl-3-dev -y && \
wget https://downloads.open-mesh.org/batman/releases/batman-adv-2020.4/batctl-2020.4.tar.gz &&  \
tar -xvf batctl-2020.4.tar.gz && \
cd batctl-2020.4 && \
make -j 4 && \
sudo make install
```

Might be worth writing to the raspberry pi people and asking them to update the package instead of having to change the batctl version every kernel update

Also, had an issue with pinging/ connecting to nodes, fixed it by changing the MTU value of bat0 to 1400 and leaving wlan0 as 1500

@binnes

**Comment by steros76** [comment] 2021-03-04 07:33
I updated only batctl as you described. Now I see the other device as neighbour but not as originator.
MTU is 1400 but ping is not working.
Any hint?

**Comment by jw2476** [comment] 2021-03-04 08:25
Could u send the output of ifconfig and sudo batctl n please? @steros76

**Comment by steros76** [comment] 2021-03-04 09:30
I have 2 Raspberry Pi Zero W: batman1 (the gateway) with an external usb wifi for connect to the standard router and batman2.
I use onboard wlan0 for batman.

Here are the logs you requested:

```
root@batman1:~# ifconfig
bat0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1400
        inet 192.168.2.1  netmask 255.255.255.0  broadcast 192.168.2.255
        inet6 fe80::f814:ee66:f819:4297  prefixlen 64  scopeid 0x20<link>
        ether be:a7:8c:5d:6c:0e  txqueuelen 1000  (Ethernet)
        RX packets 59  bytes 3480 (3.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 16  bytes 1700 (1.6 KiB)
        TX errors 0  dropped 51 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 6  bytes 522 (522.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6  bytes 522 (522.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::ba27:ebff:fe7b:879a  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:7b:87:9a  txqueuelen 1000  (Ethernet)
        RX packets 471  bytes 29822 (29.1 KiB)
        RX errors 0  dropped 3  overruns 0  frame 0
        TX packets 1425  bytes 140536 (137.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlx00e04cfb40ae: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.76  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::fb74:8472:4a0a:2198  prefixlen 64  scopeid 0x20<link>
        ether 00:e0:4c:fb:40:ae  txqueuelen 1000  (Ethernet)
        RX packets 479  bytes 64886 (63.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 351  bytes 61392 (59.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@batman1:~# batctl n
[B.A.T.M.A.N. adv 2020.4, MainIF/MAC: wlan0/b8:27:eb:7b:87:9a (bat0/be:a7:8c:5d:6c:0e BATMAN_IV)]
IF             Neighbor              last-seen
        wlan0     b8:27:eb:1b:cc:89    0.140s

root@batman1:~# batctl ping b8:27:eb:1b:cc:89
PING b8:27:eb:1b:cc:89 (b8:27:eb:1b:cc:89) 20(48) bytes of data
Reply from host b8:27:eb:1b:cc:89 timed out
Reply from host b8:27:eb:1b:cc:89 timed out
Reply from host b8:27:eb:1b:cc:89 timed out


-----


root@batman2:~# ifconfig
bat0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1400
        inet 192.168.2.2  netmask 255.255.255.0  broadcast 192.168.2.255
        inet6 fe80::7602:c34a:a5e:e693  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::880:38ff:fea7:ff87  prefixlen 64  scopeid 0x20<link>
        ether 0a:80:38:a7:ff:87  txqueuelen 1000  (Ethernet)
        RX packets 60  bytes 2588 (2.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4  bytes 1218 (1.1 KiB)
        TX errors 0  dropped 62 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 3  bytes 197 (197.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3  bytes 197 (197.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::ba27:ebff:fe1b:cc89  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:1b:cc:89  txqueuelen 1000  (Ethernet)
        RX packets 20  bytes 2586 (2.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 506  bytes 52084 (50.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@batman2:~# batctl n
[B.A.T.M.A.N. adv 2020.4, MainIF/MAC: wlan0/b8:27:eb:1b:cc:89 (bat0/0a:80:38:a7:ff:87 BATMAN_IV)]
IF             Neighbor              last-seen
        wlan0     b8:27:eb:7b:87:9a   27.730s

root@batman2:~# batctl ping b8:27:eb:1b:cc:89
PING b8:27:eb:1b:cc:89 (b8:27:eb:1b:cc:89) 20(48) bytes of data
From b8:27:eb:1b:cc:89: Destination Host Unreachable (icmp_seq 1)
From b8:27:eb:1b:cc:89: Destination Host Unreachable (icmp_seq 2)
From b8:27:eb:1b:cc:89: Destination Host Unreachable (icmp_seq 3)
```
The starting script for batman1 is the following:
```
#!/bin/bash
# batman-adv interface to use

REALNET=wlx00e04c2cac7a

batctl if add wlan0
ifconfig bat0 mtu 1400

# Tell batman-adv this is a gateway client
batctl gw_mode server

# Enable port forwarding
sysctl -w net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -o REALNET -j MASQUERADE
iptables -A FORWARD -i $REALNET -o bat0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i bat0 -o $REALNET -j ACCEPT

# Activates batman-adv interfaces
ifconfig wlan0 up
ifconfig bat0 up
ifconfig bat0 192.168.2.1/24
```
And this is the one for batman2:
```
#!/bin/bash
# batman-adv interface to use
batctl if add wlan0
ifconfig bat0 mtu 1400

# Tell batman-adv this is a gateway client
batctl gw_mode client

# Activates batman-adv interfaces
ifconfig wlan0 up
ifconfig bat0 up

ifconfig bat0 192.168.2.2/24
```

**Comment by jw2476** [comment] 2021-03-04 09:39
Try using the standard ping instead of the batctl one.

**Comment by steros76** [comment] 2021-03-04 11:00
Same thing.
```
root@batman1:~# ping 192.168.2.2
PING 192.168.2.2 (192.168.2.2) 56(84) bytes of data.
From 192.168.2.1 icmp_seq=1 Destination Host Unreachable
From 192.168.2.1 icmp_seq=2 Destination Host Unreachable
From 192.168.2.1 icmp_seq=3 Destination Host Unreachable
```
```
root@batman2:~# ping 192.168.2.1
PING 192.168.2.1 (192.168.2.1) 56(84) bytes of data.
From 192.168.2.2 icmp_seq=1 Destination Host Unreachable
From 192.168.2.2 icmp_seq=2 Destination Host Unreachable
From 192.168.2.2 icmp_seq=3 Destination Host Unreachable
```

**Comment by jw2476** [comment] 2021-03-04 11:10
Something is wrong with the startup scripts if it's unreachable, they aren't connecting 2 each other.

**Comment by steros76** [comment] 2021-03-04 11:23
I tried with "batctl tcpdump bat0" bat I can't see any packet coming from the other host.
If they are visible each other other as neighbours, the wifi config should be ok, isn't it?
I used this configuration:
```
iface wlan0 inet manual
    wireless-channel 5
    wireless-essid srmesh
    wireless-mode ad-hoc
```
Another doubt: no originators are visible... is this correct?

**Comment by jw2476** [comment] 2021-03-04 11:33
There should be sudo at the beginning of most of the commands in the scripts. Also, the IP address on the standard/ non-gateway node shouldn't have its IP set by ifconfig, it should be given an address by the gateway's DHCP server.

**Comment by steros76** [comment] 2021-03-04 12:12
There's no sudo because I used root user directly. If I don't assign ip on client host I get a 169.254.x.x address (surely because they don't talk each other).
I can't figure out where the problem could be in the full stack.
When I have more time I will test the same configuration on Raspberry PI 3 using ethernet to detect if the problem is on batman or on wifi.

**Comment by Cway14** [comment] 2021-06-02 16:24
I understand this issue is closed but leaving this here in case it helps someone else:

The issue for me was that the batctl installed using `sudo apt-get install batctl` is too old and therefore was resolved by updating the package:

1. Remove the package - `sudo apt-get remove batctl`
2. Clone the repo with up to date version - `git clone https://git.open-mesh.org/batctl.git`
3. Change directory - `cd batctl`
4. Compile package - `sudo make install`
5. Reboot - `sudo reboot`

**Comment by binnes** [comment] 2021-11-29 14:00
THIS WORKSHOP IS NO LONGER BEING MAINTAINED - CLOSING AS ARCHIVING REPO

**Closed as completed by binnes** 2021-11-29 14:00 UTC
